### ISSUE TITLE
前端请求出错

### ISSUE THREAD

**Issue by songning4** [1307super/gea-ui#1]
配置文件内容
![image](https://user-images.githubusercontent.com/65797035/125551974-a84d3af7-b325-4a49-8f50-c45cd359a6fd.png)

启动后访问网站报错
![image](https://user-images.githubusercontent.com/65797035/125552143-8b74924b-db1d-4b1d-9700-c5349de475d7.png)

**Comment by 1307super** [comment]
> 配置文件内容
> ![image](https://user-images.githubusercontent.com/65797035/125551974-a84d3af7-b325-4a49-8f50-c45cd359a6fd.png)
> 
> 启动后访问网站报错
> ![image](https://user-images.githubusercontent.com/65797035/125552143-8b74924b-db1d-4b1d-9700-c5349de475d7.png)

后端项目用最新的就可以了 已经修复了的

**Comment by songning4** [comment]
> > 配置文件内容
> > ![image](https://user-images.githubusercontent.com/65797035/125551974-a84d3af7-b325-4a49-8f50-c45cd359a6fd.png)
> > 启动后访问网站报错
> > ![image](https://user-images.githubusercontent.com/65797035/125552143-8b74924b-db1d-4b1d-9700-c5349de475d7.png)
> 
> 后端项目用最新的就可以了 已经修复了的

后端项目我clone的是master呀

**Comment by 1307super** [comment]
> > > 配置文件内容
> > > ![image](https://user-images.githubusercontent.com/65797035/125551974-a84d3af7-b325-4a49-8f50-c45cd359a6fd.png)
> > > 启动后访问网站报错
> > > ![image](https://user-images.githubusercontent.com/65797035/125552143-8b74924b-db1d-4b1d-9700-c5349de475d7.png)
> > 
> > 
> > 后端项目用最新的就可以了 已经修复了的
> 
> 后端项目我clone的是master呀

已经修复, 拉一下后端最新代码然后重启就好了
